CREATE TABLE IF NOT EXISTS JOBS(
    TITLE NVARCHAR(200) NOT NULL
    , OCCUPATION NVARCHAR(200) NOT NULL
    , SALARY NVARCHAR(200) NOT NULL
    , WORK_LOCATION NVARCHAR(200) NOT NULL
    , WORKING_HOURS NVARCHAR(200) NOT NULL
    , CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
)